name: englico
description: "Englico"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_messaging: ^14.0.1
  cloud_firestore: ^4.0.1
  firebase_storage: ^11.0.1
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.9.0
  path: ^1.8.3
  json_annotation: ^4.8.1
  google_sign_in: ^6.2.1
  weather_animation: ^1.0.1
  flutter_card_swiper: ^7.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/star.png
    - assets/ui/
    - assets/gifs/
    - assets/ills/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
